### ISSUE TITLE
Лаб 2

### ISSUE THREAD

**Issue by lasbio** [ArtyomKuzmin/db-labs#1]
1. Отсутствуют комментарии
2.  Задание 9 - не эффективно.  Можно записать условие непосредственно на joindate.  Поле joindate проиндексировано, значит, при наложение условия на него будут быстрая фильтрация. Когда вы накладываете на его части (месяц, год), то индекс не используется, значит фильтрация будет идти медленно.
3. Задание 10 - не верно. По заданию надо с начала отбоюрать 10, потом отсортировать.

**Comment by ArtyomKuzmin** [comment]
Добрый вечер, исправил ещё пару дней назад, не знал что об этом нужно уведомлять вас, поэтому пишу комментарий только сейчас.
1. Добавил комментарии.
2. Задание 9 доработал.
3. Задание 10 исправил.

**Comment by lasbio** [comment]
Оба задания (9 и 10) - не выполнены. Ничего из перечисленных ранее ошибок не поправлено.

**Comment by ArtyomKuzmin** [comment]
Здравствуйте! 
1. Задание 9 сделал более эффективным.
2. Задание 10 переделал.

**Comment by lasbio** [comment]
10 - что будет если удалить 3,5,10.

**Comment by ArtyomKuzmin** [comment]
Да, нелогично получилось... Исправил задание 10.
